hidden the auto_log
PaddlePaddle/PaddleSpeech pull request #1014
Opened 2021-11-19 13:34 UTC by Jackwaterveg

### PR types
Others

### PR changes
Others

### Describe

2021-11-19 13:47 UTC, ZeyuChen commented on paddlespeech/s2t/exps/deepspeech2/bin/test_export.py
> +        "--enable-auto-log", action="store_true", help="use auto log")
default得设置为false？

2021-11-19 13:47 UTC, ZeyuChen commented on paddlespeech/s2t/exps/deepspeech2/model.py
> +                self.autolog.times.stamp()
连续stamp两次是正确的吗

2021-11-19 13:51 UTC, Jackwaterveg commented on paddlespeech/s2t/exps/deepspeech2/model.py
> +                self.autolog.times.stamp()
这两个stamp之间是计算后处理的时间，目前没有后处理

2021-11-19 13:53 UTC, Jackwaterveg commented on paddlespeech/s2t/exps/deepspeech2/bin/test_export.py
> +        "--enable-auto-log", action="store_true", help="use auto log")
这里直接仿写了tts的autolog，测试结果确实是默认值为false

2021-11-20 10:25 UTC, zh794390558 commented on paddlespeech/s2t/exps/deepspeech2/model.py
> +                self.autolog.times.start()
加上注释，注明下是采集哪个时间。

2021-11-20 10:56 UTC, Jackwaterveg commented on paddlespeech/s2t/exps/deepspeech2/model.py
> +                self.autolog.times.start()
done

2021-11-21 00:04 UTC, ZeyuChen requested changes
测试相关目录一律移动到PaddleSpeech/tests/目录中
后续相关全链条测试都放在里面，无须对用户暴露

2021-11-21 00:04 UTC, ZeyuChen commented on paddlespeech/s2t/exps/deepspeech2/bin/test_export.py
>          "--export_path", type=str, help="path of the jit model to save")
应该将这些test目录挪出paddlespeech pypi主目录，全部放到 PaddleSpeech/tests/目录下作为单侧只对测试人员暴露。
现在全部做进exps后，会导致pypi代码庞大不少，且引入大量无关依赖。

2021-11-21 00:09 UTC, ZeyuChen commented
由于拆分wheel包了，后续整体开发理念需将wheel包定位为library，然后由外部的examples/tests/demos/脚本来进行调用library的使用。
而不是让用户进入wheel包内进行启动脚本，所以bin相关的东西需要逐步往外移。
轻wheel包，重examples 
@zh794390558

2021-11-21 10:10 UTC, zh794390558 approved these changes
这个需求我们再讨论下。暂时先合入这个PR，便于测试paddelspeech wheel包。等讨论后再修改。

2021-11-21 10:11 UTC, merged