[Setup]refactor the version
PaddlePaddle/PaddleSpeech pull request #1361
Opened 2022-01-17 12:56 UTC by Jackwaterveg

fix #1354

2022-01-17 14:27 UTC, yt605155624 commented on paddlespeech/__init__.py
> +    from .version import full_version as __version__
version 文件没有上传吗

2022-01-17 14:31 UTC, yt605155624 submitted a review, later dismissed
LGTM

2022-01-18 04:41 UTC, zh794390558 requested changes
参看 https://github.com/csukuangfj/kaldifeat/blob/master/setup.py#L18 做修改吧。目前的方案不安装无法使用。

2022-01-19 03:06 UTC, zh794390558 approved these changes
LGTM

2022-01-19 03:07 UTC, merged