add an g2p example
PaddlePaddle/PaddleSpeech pull request #623
Opened 2021-05-18 06:57 UTC by iclementine

### PR types

Others

### PR changes

Others

### Describe

Add an example to convert transcriptions from Baker dataset into pinyin.

2021-05-18 06:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/DeepSpeech?pullRequest=623) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/DeepSpeech?pullRequest=623) before we can accept your contribution.<br/><hr/>**iclementine** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/DeepSpeech?pullRequest=623) it.</sub>

2021-05-18 07:34 UTC, zh794390558 requested changes

2021-05-18 07:34 UTC, zh794390558 commented on examples/chinese_g2p/requirements.txt
> +pypinyin
pypinyin可以不用安装了。主目录的 setup.sh 会安装。

2021-05-18 07:34 UTC, zh794390558 commented on examples/chinese_g2p/data/README.md
> +# Download Baker dataset
README.md放到上一级目录，data目录可以删除。download脚本或run.sh 创建 data 目录。

2021-05-18 07:34 UTC, zh794390558 commented on examples/chinese_g2p/local/data_download.sh
> +DOWNLOAD_DIR=$(dirname $0)/../data
DOWNLOAD_DIR 可以参数传入。

2021-05-18 07:34 UTC, zh794390558 commented on examples/chinese_g2p/local/data_download.sh
> +mkdir -p ${DOWNLOAD_DIR}
这部分放到run.sh 可以会好些。

2021-05-18 07:34 UTC, zh794390558 commented on examples/chinese_g2p/local/extract_pinyin.py
> +    with open(source, 'rt', encoding='utf-8') as f:
f -> fin, g->fout

2021-05-18 07:34 UTC, zh794390558 commented on examples/chinese_g2p/local/data_download.sh
> +DOWNLOAD_DIR=$(dirname $0)/../data
source ${MAIN_ROOT}/utils/parse_options.sh 这个可以用来解析参数。

2021-05-18 07:34 UTC, zh794390558 commented on examples/chinese_g2p/run.sh
> +LABEL_FILE='ProsodyLabeling/000001-010000.txt'
变量放到一起，都小写即可。

2021-05-18 07:48 UTC, iclementine commented on examples/chinese_g2p/data/README.md
> +# Download Baker dataset
okay，虽然这个数据集还是需要手动下载

2021-05-18 08:50 UTC, iclementine commented on examples/chinese_g2p/local/data_download.sh
> +DOWNLOAD_DIR=$(dirname $0)/../data
okay

2021-05-18 08:51 UTC, iclementine commented on examples/chinese_g2p/local/extract_pinyin.py
> +    with open(source, 'rt', encoding='utf-8') as f:
已经修改

2021-05-18 08:51 UTC, iclementine commented on examples/chinese_g2p/run.sh
> +LABEL_FILE='ProsodyLabeling/000001-010000.txt'
已经修改

2021-05-18 08:56 UTC, iclementine commented on examples/chinese_g2p/local/data_download.sh
> +mkdir -p ${DOWNLOAD_DIR}
已经修改

2021-05-18 08:56 UTC, iclementine commented on examples/chinese_g2p/requirements.txt
> +pypinyin
已经修改

2021-05-18 09:03 UTC, zh794390558 requested changes

2021-05-18 09:03 UTC, zh794390558 commented on examples/chinese_g2p/local/extract_pinyin.py
> +                    fout.write(f'\t{transcription}\n')
输出文件也保持： utt transcript格式。

2021-05-18 09:03 UTC, zh794390558 commented on examples/chinese_g2p/README.md
> +Baker dataset has to be downloaded mannually and moved to 'data/', because you will have to pass the CATTCHA from a browswe to download the dataset.
给个数据集的地址。

2021-05-18 09:03 UTC, zh794390558 commented on examples/chinese_g2p/local/prepare_dataset.sh
> +mv ${filename} ${exp_dir}
copy not mv

2021-05-18 09:04 UTC, iclementine commented on examples/chinese_g2p/local/extract_pinyin.py
> +                    fout.write(f'\t{transcription}\n')
之所以这么做是为了和数据集中的 Prosody 一致方便 diff.
是要改成什么样子呢？

2021-05-18 09:06 UTC, iclementine commented on examples/chinese_g2p/local/prepare_dataset.sh
> +mv ${filename} ${exp_dir}
unrar 这样子默认是解压到当前目录。但是目的是解压到 exp_dir, 为了不留下残余的文件，所以 mv。话说有办法直接解压到 exp_dir 吗？

2021-05-18 09:08 UTC, iclementine commented on examples/chinese_g2p/README.md
> +Baker dataset has to be downloaded mannually and moved to 'data/', because you will have to pass the CATTCHA from a browswe to download the dataset.
done

2021-05-19 02:18 UTC, zh794390558 commented on examples/chinese_g2p/local/prepare_dataset.sh
> +mv ${filename} ${exp_dir}
解压到data是正常的。copy一份过去就行。

2021-05-19 02:19 UTC, zh794390558 commented on examples/chinese_g2p/local/extract_pinyin.py
> +                    fout.write(f'\t{transcription}\n')
按照 utt transcript格式即可，对比diff用vimdiff工具来比。

2021-05-19 06:28 UTC, iclementine commented on examples/chinese_g2p/local/prepare_dataset.sh
> +mv ${filename} ${exp_dir}
如果在这个 example 的目录执行 run.sh 会解压到当前目录，而不是 data 目录。

2021-05-19 06:59 UTC, zh794390558 commented on examples/chinese_g2p/local/prepare_dataset.sh
> +mv ${filename} ${exp_dir}
unrar e test.rar 解压文件到当前目录

  unrar x test.rar /path/to/extract

2021-05-19 11:26 UTC, zh794390558 approved these changes
LGTM

2021-05-19 11:26 UTC, merged