revise from_pretrained function
PaddlePaddle/PaddleSpeech pull request #684
Opened 2021-06-23 05:51 UTC by 745165806

### PR types

### PR changes
修改了from_pretrained 函数以及调用相关组件的函数中的dataset-->dataloader  的bug

### Describe

2021-06-23 05:56 UTC, zh794390558 commented on deepspeech/exps/deepspeech2/bin/deploy/runtime.py
>      config.data.keep_transcription_text = True
85 augmentation_config 应该没有了。

2021-06-23 05:57 UTC, zh794390558 commented on deepspeech/exps/deepspeech2/bin/deploy/server.py
>      config.data.keep_transcription_text = True
38 一样。

2021-06-23 05:58 UTC, zh794390558 commented on deepspeech/exps/deepspeech2/bin/deploy/server.py
> +    model = DeepSpeech2Model.from_pretrained(test_loader, config,
53 行的 feature = dataset.process_utterance(filename, "") ，deploy下的文件需要运行通过。

2021-06-23 05:59 UTC, zh794390558 commented on deepspeech/exps/deepspeech2/bin/deploy/runtime.py
> +    model = DeepSpeech2Model.from_pretrained(test_loader, config,
100 feature = dataset.process_utterance(filename, "")

2021-06-23 05:59 UTC, zh794390558 requested changes
需要验证下deploy是否能正常执行。ckpt可以从我的目录中获取。

2021-06-23 09:35 UTC, zh794390558 commented on deepspeech/exps/deepspeech2/bin/deploy/runtime.py
> +        feature = collate_fn.process_utterance(filename, "")
test_loader.collate_fn

2021-06-25 05:26 UTC, 745165806 commented
> 需要验证下deploy是否能正常执行。ckpt可以从我的目录中获取。

可以运行

2021-06-25 05:49 UTC, zh794390558 approved these changes
LGTM

2021-06-25 05:49 UTC, merged