[Add feature] CTC online , only support batch_size =1
PaddlePaddle/PaddleSpeech pull request #821
Opened 2021-09-10 09:24 UTC by Jackwaterveg

### PR types
New features

### PR changes
Others

### Describe
增加了CTC的online解码的功能，目前支持batch size=1的情况。

2021-09-10 10:01 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +void ctc_beam_search_decoder_chunk_begin(PathTrie *root, Scorer *ext_scorer) {
ctc_beam_search_decode_chunk_begin

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +std::vector<std::pair<double, std::string>> ctc_beam_search_decoder_chunk(
ctc_beam_search_decode_chunk

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +            static_cast<fst::StdVectorFst *>(ext_scorer->dictionary);
看这部分每次new了个wfst graph出来，这部分是不是不会修改的？后续可以用shared_ptr？

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +CtcBeamSearchDecoderBatch::ctc_beam_search_decoder_batch(
ctc_beam_search_decode_batch
batch的还差什么？

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +    const std::vector<std::vector<std::vector<double>>> &probs_split,
加些注释，输入是 B， T， D

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +    std::vector<std::vector<std::pair<double, std::string>>> res_tmp;
res_tmp没有用。

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +    this->batch_size = batch_size;
this->decoder_storage_vector.reserve(batch_size)

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +        this->decoder_storage_vector.push_back(decoder_storage);
push_back -> emplace_back

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +    this->root->score = root->log_prob_b_prev = 0.0;
score注释下是在 log scale 。这两个赋值拆开。注释Prob=1.0

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +CtcBeamSearchDecoderStorage::~CtcBeamSearchDecoderStorage() {
storage & batch 这两个简单的构造和析构可以放到.h中。

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/exps/deepspeech2/model.py
> +            output_probs, output_lens, batch_trans_chunk_list = self.static_forward_online(
batch_trans_chunk_list 是什么意思？

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/exps/deepspeech2/model.py
> +            batch_trans_chunk_list(list[list[string]]) : shape[B, number_of_chunks, string_length]
怎么解释shape

2021-09-10 10:37 UTC, zh794390558 commented on deepspeech/modules/ctc.py
> +        probs_split = [probs_seq.tolist() for probs_seq in probs_split]
两句合成一句吧

2021-09-13 09:24 UTC, Jackwaterveg commented on deepspeech/exps/deepspeech2/model.py
> +            batch_trans_chunk_list(list[list[string]]) : shape[B, number_of_chunks, string_length]
batch_size, chunk的数目（每个chunk都有一个结果），结果的长度

2021-09-13 09:25 UTC, Jackwaterveg commented on deepspeech/exps/deepspeech2/model.py
> +            output_probs, output_lens, batch_trans_chunk_list = self.static_forward_online(
一个batch的数据的每一个chunk输入后的结果

2021-09-13 09:26 UTC, Jackwaterveg commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +CtcBeamSearchDecoderBatch::ctc_beam_search_decoder_batch(
对于chunk级别的解码，有可能最后几个chunk中有些数据为空，就需要在C++部分增加对于输入为空的情况的处理。

2021-09-13 09:27 UTC, Jackwaterveg commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +            static_cast<fst::StdVectorFst *>(ext_scorer->dictionary);
这部分代码应该是似乎只适用于英文（! ext_scorer->is_character_based()）的。后续是可以考虑用share_ptr

2021-09-13 10:11 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +            this->decoder_storage_vector[i]->root, ext_scorer);
这种写法不支持替换词表和ext scorer

2021-09-13 10:11 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +    Scorer *ext_scorer) {
ext_scorer 可以从类中获取

2021-09-13 10:11 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.cpp
> +CtcBeamSearchDecoderBatch::decode(Scorer *ext_scorer) {
同样不需要ext_scorer。这里用threadpool 是为了什么？这里是否必要考虑多条的解码？感觉可以做单条的解码。

2021-09-13 10:11 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.h
> +    void next(const std::vector<std::vector<std::vector<double>>> &probs_split,
只解码一条的话，就不会用chunk输入为空的情况了。

2021-09-13 10:11 UTC, zh794390558 commented on deepspeech/decoders/swig_wrapper.py
> +def get_ctc_beam_search_chunk_decoder(vocabulary, batch_size, beam_size,
直接暴露出class吧，需要func了。

2021-09-13 10:11 UTC, zh794390558 commented on deepspeech/exps/deepspeech2/model.py
> +            self.model.decoder.init_decode(cfg.alpha, cfg.beta,
如果验证通过后，可以用类的方法重新实现下offline。func的输入参数也可以简化。

2021-09-13 10:11 UTC, zh794390558 commented on deepspeech/exps/deepspeech2/model.py
> +            trans = self.model.decode_get_trans()
decode_get_trans需要支持one best, n beam的返回。

2021-09-13 10:11 UTC, zh794390558 commented on deepspeech/models/ds2_online/deepspeech2.py
> +        self.decoder.chunk_decoder_next(self.chunk_decoder, probs, probs_len)
这种调用很没有必要。

2021-09-14 05:32 UTC, Jackwaterveg commented on deepspeech/models/ds2_online/deepspeech2.py
> +        self.decoder.chunk_decoder_next(self.chunk_decoder, probs, probs_len)
增加了 self.decoder.chunk_decoder_next函数中的内容，支持batch_size > 1的chunk解码

2021-09-14 07:09 UTC, zh794390558 commented on deepspeech/decoders/swig/ctc_beam_search_decoder.h
> +        this->root = new PathTrie();
new 的对象在哪儿里释放？使用 unique_ptr 智能指针。

2022-01-19 10:46 UTC, zh794390558 commented on paddlespeech/s2t/exps/deepspeech2/model.py
> +        # check the decode chunk result is same to the original decode result
这个什么意思？

2022-01-19 10:46 UTC, zh794390558 commented on paddlespeech/s2t/exps/deepspeech2/model.py
> +                              decode_cfg,
decode_cfg的配置展开吧。不用cfg作为参数。

2022-01-19 10:46 UTC, zh794390558 commented on paddlespeech/s2t/exps/deepspeech2/model.py
> +                self.model.decode_get_next(
用 self.model.decoder.decode ?

2022-01-19 10:46 UTC, zh794390558 commented on paddlespeech/s2t/exps/deepspeech2/model.py
> +                trans_best, trans_beam = self.model.decode_get_trans()
类似？

2022-01-19 10:46 UTC, zh794390558 commented on paddlespeech/s2t/models/ds2_online/deepspeech2.py
> +        trans_best, trans_beam = self.decoder.chunk_decoder_decode(
chunk_decoder_decode 这个名字看不出来干什么的。

2022-01-19 10:46 UTC, zh794390558 commented on paddlespeech/s2t/modules/ctc.py
> +    from paddlespeech.s2t.decoders.ctcdecoder.swig_wrapper import get_ctc_beam_search_chunk_decoder  # noqa: F401
stream/non-stream的接口是可以统一的。

2022-01-20 07:03 UTC, Jackwaterveg commented on paddlespeech/s2t/modules/ctc.py
> +    from paddlespeech.s2t.decoders.ctcdecoder.swig_wrapper import get_ctc_beam_search_chunk_decoder  # noqa: F401
done

2022-01-20 08:33 UTC, zh794390558 commented on examples/other/1xt2x/src_deepspeech2x/models/ds2/deepspeech2.py
> +        trans_best, trans_beam = self.decoder.decode()
trans_beam 这个是什么？

2022-01-20 08:33 UTC, zh794390558 commented on paddlespeech/s2t/exps/deepspeech2/model.py
> +        return output_probs, output_lens, trans_process_list
trans_process_list -> trans

2022-01-20 08:33 UTC, zh794390558 commented on paddlespeech/s2t/exps/deepspeech2/model.py
> +        return output_probs, output_lens, trans_process_list
L480加上 trans的type hint

2022-01-20 08:33 UTC, zh794390558 commented on paddlespeech/s2t/models/ds2/deepspeech2.py
> +        self.decoder.init_decoder(batch_size, vocab_list, decoding_method,
load lm耗时。

2022-01-20 08:33 UTC, zh794390558 commented on paddlespeech/s2t/models/u2/u2.py
> +        ctc = CTCDecoderBase(
这个是为了不引入 ctcdecoder的内容是吗?

2022-01-20 08:33 UTC, zh794390558 commented on paddlespeech/s2t/modules/ctc.py
> +    def get_decoder(self, vocab_list, batch_size, beam_alpha, beam_beta,
养成加 docstring/type hint的习惯。默认用google的风格。

2022-01-20 08:33 UTC, zh794390558 commented on paddlespeech/s2t/decoders/ctcdecoder/swig_wrapper.py
> +    return paddlespeech_ctcdecoders.CtcBeamSearchDecoderBatch
参照Scorer的方式暴露class吧。

2022-01-21 10:23 UTC, zh794390558 commented on paddlespeech/s2t/decoders/ctcdecoder/swig_wrapper.py
> +class CTC_beam_search_decoder(
CTCBeamSearchDecoder 类名驼峰式

2022-01-21 10:23 UTC, zh794390558 commented on paddlespeech/s2t/modules/ctc.py
>          from paddlespeech.s2t.decoders.ctcdecoder.swig_wrapper import Scorer  # noqa: F401
CTC_beam_search_decoder 没有import

2022-01-21 10:23 UTC, zh794390558 commented on paddlespeech/s2t/modules/ctc.py
> +            vocab_list ([list]): [List of tokens in the vocabulary, for decoding.]
【】是需要删除的

2022-01-24 02:18 UTC, zh794390558 approved these changes
LGTM

2022-01-24 02:20 UTC, zh794390558 requested changes
![image](https://user-images.githubusercontent.com/3038472/150711744-07cbe918-1321-4e37-86b0-8c6a32d4d818.png)

2022-01-24 02:22 UTC, zh794390558 commented on paddlespeech/s2t/decoders/ctcdecoder/swig_wrapper.py
> +        vocab_list (list): [Vocabulary list.]
vocab_list (list): Vocabulary list.

docstring后面的 【】也是要删除的。

2022-01-24 02:22 UTC, zh794390558 commented on paddlespeech/s2t/modules/ctc.py
> +            vocab_list (list): [List of tokens in the vocabulary, for decoding.]
docstring

2022-01-24 02:22 UTC, zh794390558 commented on paddlespeech/s2t/modules/ctc.py
> +            vocab_list (list): [List of tokens in the vocabulary, for decoding.]
docstring

2022-01-24 02:22 UTC, zh794390558 commented on paddlespeech/s2t/modules/ctc.py
> +            vocab_list (list): [List of tokens in the vocabulary, for decoding.]
docstring

2022-01-24 02:22 UTC, zh794390558 commented on paddlespeech/s2t/modules/ctc.py
> +            probs (list(list(float))): [probs for a batch of data]
docstring

2022-01-24 02:22 UTC, zh794390558 commented on paddlespeech/s2t/modules/ctc.py
> +            results_best (list(str)): [The best result for a batch of data]
docstring

2022-01-24 09:27 UTC, merged