[TTS]add csmsc mb melgan example
PaddlePaddle/PaddleSpeech pull request #935
Opened 2021-10-26 11:46 UTC by yt605155624

The model is training now..

2021-10-28 10:38 UTC, zh794390558 requested changes

2021-10-28 10:38 UTC, zh794390558 commented on parakeet/exps/gan_vocoder/multi_band_melgan/synthesize.py
> +            speed = wav.size / t.elapse
加上RTF的计算

2021-10-28 10:38 UTC, zh794390558 commented on parakeet/exps/gan_vocoder/multi_band_melgan/train.py
> +        trainer.extend(VisualDL(writer), trigger=(1, 'iteration'))
LogWriter可以直接放到VisualDL里，不用每次都实例化。

2021-10-28 10:38 UTC, zh794390558 commented on parakeet/models/melgan/melgan.py
> +from paddle.fluid.layers import Normal
不用fluid的api

2021-10-28 10:38 UTC, zh794390558 commented on parakeet/models/melgan/melgan.py
> +                        upsample_scale * 2,
这个为什么硬编码2？

2021-10-28 10:38 UTC, zh794390558 commented on parakeet/models/melgan/melgan.py
> +            Output tensor (out_channels*T ** prod(upsample_scales), 1).
为什么shape最后是1？有什么特殊考虑？

2021-10-28 10:38 UTC, zh794390558 commented on parakeet/models/melgan/melgan.py
> +    def apply_weight_norm(self):
apply_weight_norm
remove_weight_norm
reset_parameters
这些如果一直是必要的可以抽象成一个新的Layer类，后面的模型继承这个新Layer，可以避免这么多的重复代码。

2021-10-28 10:38 UTC, zh794390558 commented on parakeet/models/melgan/melgan.py
> +            int): Number of input channels.
处理下这个

2021-10-28 10:38 UTC, zh794390558 commented on parakeet/models/melgan/melgan_updater.py
> +class PWGUpdater(StandardUpdater):
和PWG的训练有区别吗？没有区别是否需要实现两个？

2021-10-28 10:38 UTC, zh794390558 commented on parakeet/models/melgan/melgan_updater.py
> +class PWGEvaluator(StandardEvaluator):
同上

2021-10-28 10:38 UTC, zh794390558 commented on parakeet/models/parallel_wavegan/parallel_wavegan.py
> -    def inference(self, c=None):
还原回原来的代码，注明动转静不支持删除的代码

2021-10-28 12:04 UTC, yt605155624 commented on parakeet/models/melgan/melgan_updater.py
> +class PWGUpdater(StandardUpdater):
这个只是复制过来还没改，已经删除.. 后续需要实现的时候再写

2021-10-28 12:05 UTC, yt605155624 commented on parakeet/models/melgan/melgan.py
> +            int): Number of input channels.
done

2021-10-29 05:45 UTC, yt605155624 commented on parakeet/models/melgan/melgan.py
> +from paddle.fluid.layers import Normal
done

2021-10-29 05:50 UTC, yt605155624 commented on parakeet/models/melgan/melgan.py
> +                        upsample_scale * 2,
论文的原作者和竞品都是这么写的，论文原作：https://github.com/descriptinc/melgan-neurips/blob/master/mel2wav/modules.py

2021-10-29 05:54 UTC, yt605155624 commented on parakeet/models/melgan/melgan.py
> +            Output tensor (out_channels*T ** prod(upsample_scales), 1).
输出维度是 (T, C_out)， 这里 1 表示音频的通道数，这里是单通道，我们训练的时候都是用单通道

2021-10-29 06:16 UTC, yt605155624 commented on parakeet/exps/gan_vocoder/multi_band_melgan/train.py
> +        trainer.extend(VisualDL(writer), trigger=(1, 'iteration'))
done

2021-10-29 06:18 UTC, yt605155624 commented on parakeet/exps/gan_vocoder/multi_band_melgan/synthesize.py
> +            speed = wav.size / t.elapse
done

2021-10-29 06:21 UTC, yt605155624 commented on parakeet/models/melgan/melgan.py
> +    def apply_weight_norm(self):
这个我之后再想想怎么设置.. ，目前 apply_weight_norm remove_weight_norm 是在声码器里面用，reset_parameters仅在 melgan 里面用

2021-10-29 09:45 UTC, zh794390558 approved these changes
LGTM

2021-10-29 09:45 UTC, merged